project:
  type: website

website:
  title: "SLE Prep"
  sidebar:
    contents:
      - section: "Level A"
        contents:
          - href: index.qmd
            text: "Home"
      - section: "Level B"
        contents:
          - href: about.qmd
            text: "About"
      - section: "Level C"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
